language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
dist: precise
cache:
    directories:
      - "$HOME/.composer/cache"
# Load secure environment variables for access by other scripts
env:
  global:
    - secure: "VQRmfY0b7dwYJNH2SyO5yGyWNTir8sNeCJOMgmH6slYF+zla6s6iuc6Nt837aVORSyL/CnASPRpm1O7wYDHJpYpa+kJRmNf/n/dyi0b+WVgH/H0NeqS/qUg7TTz+BtKQHqNUQourMOQ+vM4D75zSN+R7h/lf+hOdzucsqDBXcUA="
notifications:
  slack:
    rooms:
      secure: "LegKwsGSAQDcqUGA8Jg90XUWfhnmho5U+RXKpuRfAT4L5Z8j761AVGIwTrUWw8gnxeGccr3smTWahm+GYuwMvg8YDxcygPuVn3U+fus0qgqAnfkQLmMl4vSdkZfO1GTc7YkyLAJcmwdDeUgXr94gQ4qvmsTSk8E0gzIstdfFiOU="
  on_success: change
  on_failure: always

before_script:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql
    php5-intl
  - sudo sed -i -e "s,/var/www,$(pwd)/public_html,g" /etc/apache2/sites-available/default
  - sudo sed -i -e "/DocumentRoot/i\ServerName phplist.dev" /etc/apache2/sites-available/default
  - echo "127.0.0.1 phplist.dev" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/apache2 restart
  - mkdir -p build/screenshot
  - pwd
  - cp -f tests/travis-ci/behat.yml behat.yml
  - cp -f tests/travis-ci/config.php public_html/lists/config/config.php
  - composer self-update
  - composer install --prefer-dist

  # start selenium
  - ./bin/start-selenium.sh > /dev/null 2>&1 &
  - sleep 3

  - cd vendor/bin && ln -s ../njoannidi/php-lint-bash/phpLint && cd ../../
  - ls -l vendor/bin
  - cd public_html/lists/admin/ui/ && wget https://github.com/phpList/phplist-ui-bootlist/archive/master.tar.gz
    && tar -xzf master.tar.gz && mv phplist-ui-bootlist-master phplist-ui-bootlist &&
    rm master.tar.gz && cd ../../../../
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database phplistdb;'

script:
  - vendor/bin/behat tests/features/getting-started/setup.feature
  - vendor/bin/phpLint ./public_html
  - vendor/bin/behat

after_failure:
  - IMGUR_CLIENT_ID=bec050c54e1bb52 ./bin/imgur-uploader.sh build/screenshot/*.png
  - echo "Failures detected. Outputing additional logs:"
  - sudo ls -l /etc/apache2/sites-available/
  - sudo cat /etc/apache2/apache2.conf
  - sudo cat /etc/apache2/sites-available/000-default.conf
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/mysql/error.log
