language: php

cache:
    directories:
      - "$HOME/.composer/cache"

matrix:
    include:
        - php: '5.4'
          env: BROWSER=goutte TAGS="~javascript && ~@first-run && ~@wip"
        - php: '5.5' 
          env: BROWSER=goutte TAGS="~javascript && ~@first-run && ~@wip"
        - php: '5.6'
          env: BROWSER=goutte TAGS="~javascript && ~@first-run && ~@wip"
        - php: '7.0'
          env: BROWSER=goutte TAGS="~javascript && ~@first-run && ~@wip"
        - php: '7.1'
          env: BROWSER=goutte TAGS="~javascript && ~@first-run && ~@wip"
        - php: '7.1'
          env: BROWSER=chrome TAGS="~javascript && ~@first-run && ~@wip"
        - php: '7.2'
          env: BROWSER=goutte TAGS="~javascript && ~@first-run && ~@wip"
        - php: '7.2'
          env: BROWSER=chrome TAGS="~javascript && ~@first-run && ~@wip"
        - php: '7.3'
          env: BROWSER=goutte TAGS="~javascript && ~@first-run && ~@wip"
        - php: '7.3'
          env: BROWSER=chrome TAGS="~javascript && ~@first-run && ~@wip"


notifications:
  slack:
    rooms:
      secure: "LegKwsGSAQDcqUGA8Jg90XUWfhnmho5U+RXKpuRfAT4L5Z8j761AVGIwTrUWw8gnxeGccr3smTWahm+GYuwMvg8YDxcygPuVn3U+fus0qgqAnfkQLmMl4vSdkZfO1GTc7YkyLAJcmwdDeUgXr94gQ4qvmsTSk8E0gzIstdfFiOU="
  on_success: change
  on_failure: always

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 2000x2000x16"
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - if [[ $TRAVIS_PHP_VERSION = hhvm* ]]; then export INI=/etc/hhvm/php.ini; else export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - echo memory_limit = -1 >> $INI

install:
  # install dependencies
  - composer install --prefer-dist --no-interaction

  # start php server for non php >=5.4 version
  - cp -fv tests/travis-ci/behat.yml behat.yml
  - cp -fv tests/travis-ci/config.php public_html/lists/config/config.php
  - php -S localhost:8000 -t public_html > /dev/null 2>&1 &

  # start selenium and php server
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  - ./bin/start-selenium > /dev/null 2>&1 &
  - sleep 5

  # setup database and phplist
  - mkdir -p build/screenshot
  - cd public_html/lists/admin/ui/ && wget https://github.com/phpList/phplist-ui-bootlist/archive/master.tar.gz
    && tar -xzf master.tar.gz && mv phplist-ui-bootlist-master phplist-ui-bootlist &&
    rm master.tar.gz && cd ../../../../
  - cd vendor/bin && ln -s ../njoannidi/php-lint-bash/phpLint && cd ../../
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database phplistdb;'
  - mysql -u root -e "CREATE USER 'phplist'@'localhost' IDENTIFIED BY 'phplist';"
  - mysql -u root -e "GRANT ALL ON phplistdb.* TO 'phplist'@'localhost'; FLUSH PRIVILEGES;"
  - sudo service mysql restart

before_script:
  - sudo service postfix stop
  - mkdir -p build/mails
  - cd build/mails
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - cd ${TRAVIS_BUILD_DIR}

script:
  # check syntax
  - ./vendor/bin/phpLint ./public_html

  # run setup feature first to create database
  - ./vendor/bin/behat -n -fprogress -p $BROWSER --strict --tags=@first-run

  # run all feature except @first-run
  - ./vendor/bin/behat -n -fprogress -p $BROWSER --strict --tags="${TAGS}"
addons:
  chrome: stable

after_failure:
  - ls -l build/mails
  - ls -l
  - IMGUR_CLIENT_ID=bec050c54e1bb52 ./bin/imgur-uploader.sh build/screenshot/*.png
