
name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
        experimental: [false]
        include:
          - php-version: '8.3'
            experimental: true

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

      - name: Setup Packages
        run: |
          sudo apt update
          sudo apt install -y rsync

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          args: --prefer-dist --no-interaction
          php_version: ${{ matrix.php-version }}
          php_extensions: xml
        continue-on-error: ${{ matrix.experimental }}

      - name: Report Versions
        run: |
          google-chrome --version
          lsb_release -a
          php -v
          chromedriver -v
          geckodriver -V
          which geckodriver
          which chromedriver
          firefox -v
          vendor/bin/behat -V
          mysql --version
          mysqladmin --version
        continue-on-error: ${{ matrix.experimental }}

      - name: Create Database
        run: |
          sudo systemctl start mysql.service
          sudo mysql -proot -e 'DROP DATABASE IF EXISTS phplistdb'
          sudo mysqladmin -proot create phplistdb
          sudo mysql -proot -e 'CREATE USER phplist@"%" IDENTIFIED BY "phplist"; GRANT ALL ON phplistdb.* TO phplist@"%"'
        continue-on-error: ${{ matrix.experimental }}

      - name: Set Bootlist Theme
        run: |
          cd public_html/lists/admin/ui/
          wget https://github.com/phpList/phplist-ui-bootlist/archive/master.tar.gz
          tar -xzf master.tar.gz
          mv phplist-ui-bootlist-master phplist-ui-bootlist
          rm master.tar.gz
        continue-on-error: ${{ matrix.experimental }}

      - name: Start Test Server
        run: |
          cp -fv tests/ci/behat.yml tests/behat.yml
          cp -fv tests/ci/config.php public_html/lists/config/config.php
          mkdir -p output/screenshots
          mkdir -p build/mails
          ./bin/start-selenium > output/selenium.log 2>&1 &
          sleep 5
          sudo php -S 0.0.0.0:80 -t public_html > /dev/null 2>&1 &
        continue-on-error: ${{ matrix.experimental }}

      - name: Check PHP syntax errors
        uses: overtrue/phplint@2.4.1
        with:
          path: ./public_html
        continue-on-error: ${{ matrix.experimental }}

      - name: Run BDD Tests UI
        run: |
          cd tests
          ../vendor/bin/behat -p chrome -f progress --stop-on-failure --tags=@initialise
          ../vendor/bin/behat -p chrome -f progress --tags="~@initialise && ~@wip"
        continue-on-error: ${{ matrix.experimental }}

      - name: Run BDD Tests CLI
        run: |
          export ADMIN_EMAIL=admin@phplist.dev
          export ADMIN_PASSWORD=Mypassword123+
          export ORGANISATION_NAME="phpList"
          export ADMIN_NAME="phpList Administrator"
          php public_html/lists/admin/index.php -c public_html/lists/config/config.php -p initialise -f
          cd tests
          ../vendor/bin/behat -p chrome --tags="~@initialise && ~@wip"
        continue-on-error: ${{ matrix.experimental }}

      - name: Handle Experimental Warnings
        if: ${{ matrix.experimental && failure() }}
        run: |
          echo "::warning::PHP ${matrix.php-version} tests failed. This is marked as experimental and does not impact overall workflow success."

      - name: Upload the Screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: "output"
          name: "behat output ${{ matrix.php-version }}"
          retention-days: 3

      - name: Display Output on Failure
        if: failure() && !matrix.experimental
        run: |
          find . -type f
          cat output/selenium.log
